<a href="https://colab.research.google.com/github/Priyanshi614/ML_SEM6_CE017/blob/main/ML_LAB01_CE017.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
x=5
print(x," TYPE: ",type(x))
x="Hello"
print(x," TYPE: ",type(x))
x=[1,2,3]
print(x," TYPE: ",type(x))

5  TYPE:  <class 'int'>
Hello  TYPE:  <class 'str'>
[1, 2, 3]  TYPE:  <class 'list'>


In [4]:
alist = [1,2,3,4,5]
narray = np.array([1,2,3,4,5])
blist = [5,6,7,8,9]
#narray1 = np.array([5,6,7,8]) elements should be of same shape
narray1 = np.array([5,6,7,8,9])
print(alist)
print(narray)
print(type(alist))
print(type(narray))
print(narray+narray) #element wise addition
print(alist+alist) #union including repeated values
print(narray+narray1)
print(alist+blist)
print(alist*3)
print(narray*3)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>
[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 6  8 10 12 14]
[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12 15]


In [5]:
x = np.array([[1,2],[1,2]], dtype=np.float64)
y = np.array([[2,1],[2,1]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))


[[3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]]
[[-1.  1.]
 [-1.  1.]]
[[-1.  1.]
 [-1.  1.]]
[[2. 2.]
 [2. 2.]]
[[2. 2.]
 [2. 2.]]
[[0.5 2. ]
 [0.5 2. ]]
[[0.5 2. ]
 [0.5 2. ]]


In [6]:
nx = np.array([[1,2],[1,2]], dtype=np.float64)
y = np.array([[2,1],[2,1]], dtype=np.float64)
print(x.dot(y))
print(np.sqrt(x))
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[6. 3.]
 [6. 3.]]
[[1.         1.41421356]
 [1.         1.41421356]]
[[6. 3.]
 [6. 3.]]
[[6. 3.]
 [6. 3.]]
[[6. 3.]
 [6. 3.]]


In [7]:
x = np.array([[1,2,6],[3,4,5]])
print(np.sum(x)) 
print(np.sum(x, axis=0)) 
print(np.sum(x, axis=1))
print(x)
print("transpose\n", x.T)

21
[ 4  6 11]
[ 9 12]
[[1 2 6]
 [3 4 5]]
transpose
 [[1 3]
 [2 4]
 [6 5]]


In [9]:
badmatrix = np.array([[1,2 ], [3, 4], [6,7,8]]) # Define a matrix.

print(badmatrix) # Print the malformed matrix
print(badmatrix * 2) # It is supposed to scale the whole matrix
badmatrix = np.array([[1,2 ], [3, 4], [6,7]])
result = badmatrix * 2 + 1
print(result)

[list([1, 2]) list([3, 4]) list([6, 7, 8])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([6, 7, 8, 6, 7, 8])]
[[ 3  5]
 [ 7  9]
 [13 15]]


<ipython-input-9-f11f57d3a0e9>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  badmatrix = np.array([[1,2 ], [3, 4], [6,7,8]]) # Define a matrix.


In [10]:
nparray = np.array([1, 2, 3, 4])#array
nparray = np.array([[1, 2, 3, 4]])#matrix
nparray1 = np.array([1, 2, 3, 4]) # Define an array
norm1 = np.linalg.norm(nparray1)
nparray2 = np.array([[1, 2], [3, 4]]) # if not mentioned 
norm2 = np.linalg.norm(nparray2)
print(norm1)
print(norm2)

5.477225575051661
5.477225575051661


In [11]:
#exercise

#ex1,2
nparray1 = np.array([[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4]])
nparray2 = np.array([[1, 2, 3, 4,5],[1, 2, 3, 4,5],[1, 2, 3, 4,5],[1, 2, 3, 4,5]])
print(nparray1)
print(nparray2)

#ex3
print(nparray1.dot(nparray2))
#print(np.multiply(nparray1, nparray2)) error

#ex4
print(np.multiply(nparray1, nparray2.T))

#ex5
print(np.mean(nparray1))
print(np.median(nparray1))

#ex6
sq_matrix = nparray1.dot(nparray2)
print(nparray1.T)
print(sq_matrix)
det1 = np.linalg.det(sq_matrix)
print(det1)

#ex7
print(nparray1[:,1])

#ex8

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]
 [ 5 10 15 20]]
2.5
2.5
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]]
0.0
[2 2 2 2 2]
